# Site settings
title: Lux Marketing
email: your-email@domain.com
description: Ideas que iluminan
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://luxmarketing.mx" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
